FROM node:lts-alpine

WORKDIR /usr/app

COPY package.json package-lock.json .

RUN --mount=type=cache,target=/root/.npm \
  npm install -g npm && \
  npm install --legacy-peer-deps

COPY . .

CMD ["npm", "run", "start-in-docker"]
