services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      # exposed on localhost 1434
      - "1434:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Dogfood1!
      MSSQL_PID: Express

volumes:
  sqlvolume:
